In [ ]:
import pandas as pd

pd.options.display.max_columns = None

In [ ]:
df_credit = pd.read_csv('credit_card.csv', dtype=str)
df_customer = pd.read_csv('customer.csv', dtype=str)

# standardize the column names
df_credit.columns = df_credit.columns.str.lower().str.replace(' ', '_')
df_customer.columns = df_customer.columns.str.lower().str.replace(' ', '_')

In [ ]:
df_credit.sample(5)

,client_num,card_category,annual_fees,activation_30_days,customer_acq_cost,week_start_date,week_num,qtr,current_year,credit_limit,total_revolving_bal,total_trans_amt,total_trans_vol,avg_utilization_ratio,use_chip,exp_type,interest_earned,delinquent_acc
100,708301683,Blue,125,0,89,01-01-2023,Week-1,Q1,2023,20798,1059,8038,90,0.051,Swipe,Food,2009.5,0
3082,714023808,Blue,480,1,119,16-04-2023,Week-16,Q2,2023,13770,2517,1582,36,0.183,Online,Bills,205.66,0
103,708313608,Blue,245,1,61,01-01-2023,Week-1,Q1,2023,2464,2116,2110,43,0.859,Swipe,Food,274.3,0
8466,788701608,Blue,125,1,104,29-10-2023,Week-44,Q4,2023,2950,1705,1260,32,0.578,Swipe,Fuel,352.8,0
1881,711835758,Blue,325,1,80,05-03-2023,Week-10,Q1,2023,34516,2099,1756,35,0.061,Swipe,Grocery,122.92,0

In [ ]:
df_final = pd.merge(df_customer, df_credit, on='client_num', how='left')

In [ ]:
# check duplicated value
df_final[df_final.duplicated()]

Empty DataFrame
Columns: [client_num, customer_age, gender, dependent_count, education_level, marital_status, state_cd, zipcode, car_owner, house_owner, personal_loan, contact, customer_job, income, cust_satisfaction_score, card_category, annual_fees, activation_30_days, customer_acq_cost, week_start_date, week_num, qtr, current_year, credit_limit, total_revolving_bal, total_trans_amt, total_trans_vol, avg_utilization_ratio, use_chip, exp_type, interest_earned, delinquent_acc]
Index: []

In [ ]:
# separate dataset into two
df_final.shape

(10108, 32)

In [ ]:
10108/2

5054.0

In [ ]:
# separate into 2 files
df_final.iloc[:5054].to_csv('credit_card_1.csv', index=False, sep=';')
df_final.iloc[5054:].to_csv('credit_card_2.csv', index=False, sep=';')